name: example
description: "Example project for showing how to use Gravity SDK"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  webview_flutter: ^4.10.0
  flutter_gen_core: ^5.12.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  cached_network_image: ^3.4.1

  gravity_sdk:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

